# nginx.conf
server {
    # Cloud Run expects the container to listen on 8080
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Fallback to index.html for Angular routing
        try_files $uri $uri/ /index.html;
    }
}
