server {
    listen 80; # Cloud Run will map its $PORT to this container port
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # This handles Angular's client-side routing
        try_files $uri $uri/ /index.html;
    }

    # Optional: Optimizations for static assets
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 30d;
        add_header Cache-Control "public";
    }
}
